FROM alpine:latest

# Environment variables
ENV MC_VERSION="latest" \
    PAPER_BUILD="latest" \
    EULA="true" \
    MC_RAM="" \
    JAVA_OPTS=""

COPY start.sh .
COPY server.properties .
COPY RconMonitor.class .

RUN apk update \
    && apk add libstdc++ \
    && apk add openjdk25-jre \
    && apk add bash \
    && apk add wget \
    && apk add jq

RUN wget -O /fabric-server-mc.jar https://meta.fabricmc.net/v2/versions/loader/26.1.2/0.19.2/1.1.1/server/jar

RUN mkdir /minecraft
WORKDIR /minecraft

RUN mv /fabric-server-mc.jar fabric-server-mc.jar
RUN echo "eula=TRUE" > eula.txt

WORKDIR /
# Start script
ENTRYPOINT ["./start.sh"]