view-distance=1
management-server-enabled=true
management-server-tls-enabled=false
management-server-host=localhost
management-server-port=25575
management-server-allowed-origins=*
management-server-secret=tPiEVVPAyVyoL6OEL3IZRdsBKYeMpPA4P8l7hoe3