FROM docker.io/steamcmd/steamcmd:latest AS downloader

RUN steamcmd +login anonymous +quit
RUN steamcmd \
    +force_install_dir /opt/satisfactory \
    +login anonymous \
    +app_update 1690800 validate \
    +quit

FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y libcurl4 \
    && rm -rf /var/lib/apt/lists/* \
    && useradd -m steam

COPY --from=downloader --chown=steam:steam /opt/satisfactory /home/steam/SatisfactoryDedicatedServer
COPY --chown=steam:steam start.sh /home/steam/start.sh
RUN chmod +x /home/steam/start.sh

USER steam

CMD ["/home/steam/start.sh"]